.travis.yml

travis ci for auto build upon pull-requests

added travis ci

---

launch/rs.launch
launch/rs_demo.launch
src/utils/src/run.cpp

renamed launch file to be more generic.
switched to ros parameters.
robosherlock node and launchfile have the same interface.
added machine tag and optional machine definition to launchfile.

Generic and parameterizable launch file and an identical interface for the run node

---

CMakeLists.txt
src/io/src/CollectionReader.cpp

camera config files and semantic map files are now looked up in the robosherlock config folder or any config folder in depending packages.

Improved camera config file lookup

---

src/io/src/CollectionReader.cpp
src/io/src/ResultAdvertiser.cpp

ResultAdvertiser now returns all object hypotheses and scene annotations in the form of a json string

Fixed Result Advertiser

---

descriptors/annotators/filter/RegionFilter.xml
src/core/include/rs/utils/exception.h
src/core/src/DrawingAnnotator.cpp
src/filter/src/RegionFilter.cpp
src/io/src/MongoDBBridge.cpp
src/utils/CMakeLists.txt
src/utils/include/rs/utils/RSAnalysisEngineManager.h
src/utils/src/RSAnalysisEngine.cpp

With this extension RoboSherlock will only process frames if something changed. It will only look at the filtered regions. Other cases for processing the current frame are a received query or a timeout.
Also fixed some minor bugs.

Change detection for region filter

---

descriptors/analysis_engines/demo.xml
descriptors/analysis_engines/resolution.xml
descriptors/analysis_engines/storage.xml
descriptors/annotators/filter/ClusterFilter.xml
descriptors/annotators/segmentation/PointCloudClusterExtractor.xml
descriptors/annotators/utils/ImagePreprocessor.xml
src/annotation/include/rs/annotation/web/goggles.h
src/annotation/src/PCLDescriptorExtractor.cpp
src/core/include/rs/utils/common.h
src/core/include/rs/view_names.h
src/detection/src/PlaneAnnotator.cpp
src/filter/CMakeLists.txt
src/filter/src/ClusterFilter.cpp
src/segmentation/src/PointCloudClusterExtractor.cpp
src/tracking/src/ObjectIdentityResolution.cpp
src/utils/CMakeLists.txt
src/utils/src/BlurDetectorAnnotator.cpp
src/utils/src/ClusterMerger.cpp
src/utils/src/ImagePreprocessor.cpp

Added a mask for depth image border regions, will also work with robot self filter.
Added a cluster filter based on the overlap to the border region mask.
General improvements, bug fixes, clean up.

Depth border mask and cluster filter

---

descriptors/annotators/filter/RegionFilter.xml
src/utils/src/ClusterMerger.cpp

- use the 3D points to decide which hypotheses to keep
- keep annotation of cluster that will be deleted
- if cluster can be found using 3D euclidean clustering, but hyp from a diff. source will be kept, remove PoseAnnotation

updates to Cluster Merging

---

descriptors/typesystem/annotation_types.xml
src/filter/src/RegionFilter.cpp
src/io/src/TFBroadcaster.cpp

- pose and name in clusterparts type
- changed cutoff for middle counter top
- TFBroadcaster shows poses of parts as well

improvements

---

src/tracking/src/ObjectIdentityResolution.cpp

All annotations from current cluster are getting added. Also all annotations with types that are not present in the current cluster are getting added from the previous annotations.
If there is a source field, it is taken into account as well.

New merging for OIR.

---

config/semantic_map.yaml
descriptors/annotators/filter/RegionFilter.xml
src/filter/src/RegionFilter.cpp
src/io/src/visualizer.cpp

- region filter takes an array of regions as param
- frustum check is optional in region filter
- new entry in sem map

region filter updates and sem map change

---

CMakeLists.txt
cmake/robosherlock.cmake.in
scripts/update_analysis_engines.py

- 'Fixed' update_analysis_engine. Got an unecessary parameter.
- Fixed a typo
- Added warning message if a parameter in update_analysis_engine is incorrect

Some minor cmake updates

---

config/semantic_map.yaml
descriptors/annotators/detection/PlaneAnnotator.xml
src/detection/src/PlaneAnnotator.cpp
src/filter/src/RegionFilter.cpp
src/utils/src/ClusterMerger.cpp

- cluster merger fix 
- sem map entry for open drawer and reduced size of table

enhancements

---

descriptors/annotators/tracker/ObjectIdentityResolution.xml
descriptors/typesystem/annotation_types.xml
descriptors/typesystem/scene_types.xml
src/tracking/src/ObjectIdentityResolution.cpp

added disappeared field to objects.
added fast match distance threshold.

prepared for multi-object clusters.

---

.travis.yml
cmake/robosherlock.cmake.in
config/config_kinect2.ini
package.xml
src/core/CMakeLists.txt
src/core/include/rs/utils/common.h
src/io/src/UnrealVisionBridge.cpp

- Sped up build process by using cache
- The repository does not have to be pulled explicitly, it's pulled automatically at the very beginning
- minor cmake issues
- added missing dependencies in package.xml
-> Travis should now be successful again, even with UnrealCV

Fixed some travis and cmake issues

---

config/config_kinect_robot_filtered.ini
config/config_unreal_vision.ini
src/io/include/rs/io/UnrealVisionBridge.h
src/io/src/UnrealVisionBridge.cpp

- after Sherpa review consider moving this to a different Ros package

small changes to unrelbridge

---

CMakeLists.txt
README.md
cmake/robosherlock.cmake.in

Quick fix for Ubuntu 16.04, until OpenCV compatibility is solved.

Xenial compat

---

descriptors/typesystem/annotation_types.xml
descriptors/typesystem/core_types.xml
src/annotation/src/CaffeAnnotator.cpp
src/annotation/src/FeatureAnnotator.cpp
src/core/include/rs/compare.h
src/detection/src/PlaneAnnotator.cpp
src/segmentation/src/ImageSegmentationAnnotator.cpp

- cleaned up a bit
- added descriptions to certain parts
- added a type for storing ground truth

Typesystem enhancements 

---

descriptors/analysis_engines/data_loader.xml
descriptors/analysis_engines/resolution.xml
descriptors/analysis_engines/storage.xml
descriptors/annotators/segmentation/TransparentSegmentationAnnotator.xml
descriptors/typesystem/annotation_types.xml
src/segmentation/CMakeLists.txt
src/segmentation/include/rs/segmentation/TransparentSegmentationAnnotator.h
src/segmentation/src/TransparentSegmentationAnnotator.cpp

This PR adds an annotator which detects possible regions of transparent or glossy objects.
Works with structure-light sensors (Kinect 360, Xtion)

Transparent segmentation annotator

---

cmake/robosherlock.cmake.in
descriptors/analysis_engines/demo.xml
descriptors/annotators/annotation/NormalEstimator.xml
descriptors/annotators/detection/PlaneAnnotator.xml
descriptors/annotators/filter/PointCloudFilter.xml
descriptors/annotators/filter/RegionFilter.xml
descriptors/annotators/segmentation/ImageSegmentationAnnotator.xml
descriptors/annotators/segmentation/PointCloudClusterExtractor.xml
descriptors/annotators/segmentation/TransparentSegmentationAnnotator.xml
descriptors/typesystem/pcl_types.xml

renamed one of the auxiliary types

Typesystem changes

---

descriptors/annotators/annotation/Cluster3DGeometryAnnotator.yaml
descriptors/annotators/filter/RegionFilter.yaml
descriptors/annotators/io/DrawResultImage.yaml
descriptors/annotators/segmentation/PointCloudClusterExtractor.yaml
scripts/rs_create_package
scripts/rs_new_annotator
src/flowcontrol/src/AEYamlToXML.cpp
src/flowcontrol/src/YamlToXMLConverter.cpp
src/io/CMakeLists.txt
src/io/src/DrawResultImage.cpp
src/utils/src/Trigger.cpp

**New:**
* annotator for saving results written on images; T
* Triggering can work now from a service of type ``std_srvs/Trigger``
**Fix:**
* params that are arrays in yaml generate correct xml
* scripts for generating annotators and rs dependent packages

Devel fixes

---

robosherlock/descriptors/annotators/io/StorageWriter.yaml
robosherlock/src/core/include/rs/scene_cas.h
robosherlock/src/io/src/Storage.cpp
robosherlock/src/io/src/StorageWriter.cpp

- eases accessing db entries and is in line with mongo recommendations

prepend instead of append cam ids to collection names; 

---

robosherlock/descriptors/annotators/tracker/KCFTrackingAnnotator.yaml
robosherlock/descriptors/annotators/tracker/PCLParticleTrackingAnnotator.yaml
robosherlock/owl/rs_components.owl

- tracker annotators fixed for owl generation. new owl generated

fix annotator yaml for owl generation and new owl

---

robosherlock/CMakeLists.txt
robosherlock/config/config_data_loader.ini
robosherlock/config/config_data_loader_utest.ini
robosherlock/config/semantic_map_iai_kitchen.yaml
robosherlock/descriptors/analysis_engines/u_test.yaml
robosherlock/owl/iai-kitchen-objects.owl
robosherlock/src/annotation/src/CaffeAnnotator.cpp
robosherlock/src/annotation/src/ClusterColorHistogramCalculator.cpp
robosherlock/src/core/src/DrawingAnnotator.cpp
robosherlock/src/detection/src/PlaneAnnotator.cpp
robosherlock/src/filter/src/RegionFilter.cpp
robosherlock/src/flowcontrol/src/RSAggregateAnalysisEngine.cpp
robosherlock/src/flowcontrol/src/runAAE.cpp
robosherlock/src/io/CMakeLists.txt
robosherlock/src/io/include/rs/io/CollectionReader.h
robosherlock/src/io/src/CollectionReader.cpp
robosherlock/src/io/src/DataLoaderBridge.cpp
robosherlock/src/io/src/ROSKinectBridge.cpp
robosherlock/src/io/src/ROSRealSenseBridge.cpp
robosherlock/src/io/src/visualizer.cpp
robosherlock/src/queryanswering/src/SWIPLInterface.cpp
robosherlock/src/segmentation/src/PointCloudClusterExtractor.cpp
robosherlock/src/segmentation/symmetrysegmentation/CMakeLists.txt
robosherlock/test/annotators_utest/RegionFilter_utest.cpp

* exchanged the parsing of the regions to use yaml-cpp instead of OpenCV making the handling of optional fields easier
* new rs::Exception for exceptions thrown during initialization. Should be used to send meaningful errors when things go wrong (had to do a minor change in uimacpp for this)
* added optional field for defining regions relative to a frame other than map
* changed drawers in PointCloudClusterExtractor and ColorHist annotator to use the normal image instead of the hd onw
* RealSenseBridge can now handle the optimal resolution of the D435 (848*480)

region filter and realsense bridge updates

---

.gitmodules
.travis.yml
README.md
rapidjson_ros/CMakeLists.txt
rapidjson_ros/package.xml
robosherlock/CMakeLists.txt
robosherlock/package.xml

Reverts RoboSherlock/robosherlock#196 decided for a possibly better way for doing this.

Revert "Update default branch to bionic"

---

ChangeLog.txt
robosherlock/CMakeLists.txt
robosherlock/src/queryanswering/include/robosherlock/queryanswering/SWIPLInterface.h
robosherlock/src/queryanswering/src/SWIPLInterface.cpp

updating internal Prolog engine to work with newer SWIPL

Update to swipl 8

---

robosherlock/descriptors/annotators/filter/RegionFilter.yaml
robosherlock/src/filter/src/RegionFilter.cpp

Added marker visualization and on/off switch via reconfiguration.

RegionFilter with markers
